vaadin.launch-browser=true
spring.application.name=vaadin-users
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/vaadin_users
spring.datasource.username=postgres
spring.datasource.password=123qweasdzxc
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

server.port=8080